# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/converters/php56-mbstring/Makefile 453277 2017-11-01 11:39:44Z ale $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-mbstring

.include "${MASTERDIR}/Makefile"
