# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/textproc/php56-pspell/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-pspell

.include "${MASTERDIR}/Makefile"
