# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/archivers/php56-phar/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-phar

.include "${MASTERDIR}/Makefile"
