# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php56-pdo_firebird/Makefile 480602 2018-09-24 12:01:39Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-pdo_firebird

.include "${MASTERDIR}/Makefile"
