# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php56-sqlite3/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-sqlite3

.include "${MASTERDIR}/Makefile"
