# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/net/php56-sockets/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-sockets

.include "${MASTERDIR}/Makefile"
