# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php56-pdo_pgsql/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTREVISION=	1
CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-pdo_pgsql

.include "${MASTERDIR}/Makefile"
