# $FreeBSD: head/textproc/php56-enchant/Makefile 420657 2016-08-23 10:54:49Z amdmi3 $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-enchant

.include "${MASTERDIR}/Makefile"
