# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/security/php56-openssl/Makefile 487169 2018-12-10 14:19:22Z ale $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-openssl

.include "${MASTERDIR}/Makefile"
