# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/mail/php56-imap/Makefile 487169 2018-12-10 14:19:22Z ale $

CATEGORIES=	mail

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-imap

.include "${MASTERDIR}/Makefile"
