# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/archivers/php56-zip/Makefile 453277 2017-11-01 11:39:44Z ale $

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-zip

.include "${MASTERDIR}/Makefile"
