# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/www/php56-tidy/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-tidy

.include "${MASTERDIR}/Makefile"
