# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/graphics/php56-gd/Makefile 466773 2018-04-08 06:59:57Z ale $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-gd

.include "${MASTERDIR}/Makefile"
