# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/math/php56-bcmath/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	math

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-bcmath

.include "${MASTERDIR}/Makefile"
