# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/sysutils/php56-fileinfo/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	sysutils

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-fileinfo

.include "${MASTERDIR}/Makefile"
