# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/ftp/php56-curl/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	ftp

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-curl

.include "${MASTERDIR}/Makefile"
